# Generated by Django 3.1.7 on 2021-03-04 13:48

import Account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('Logo', models.ImageField(null=True, upload_to=Account.models.create_path)),
                ('TrainingSpecialization', models.TextField(null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('CompanyName', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('Website', models.CharField(max_length=255, null=True)),
                ('MembershipNumber', models.CharField(max_length=255, null=True)),
                ('JoinedDate', models.DateTimeField(blank=True, null=True)),
                ('MembershipStartDate', models.DateTimeField(blank=True, null=True)),
                ('MembershipEndDate', models.DateTimeField(blank=True, null=True)),
                ('DateInputed', models.DateTimeField(blank=True)),
                ('RegistrationMembershipFormID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.registrationmembershipformdb')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
