# Generated by Django 3.1.7 on 2021-03-04 13:48

import Registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationMembershipFormDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Done', 'done'), ('member', 'Member')], default='pending', max_length=255)),
                ('NameofOrganisation', models.CharField(max_length=255, null=True)),
                ('Logo', models.ImageField(null=True, upload_to=Registration.models.create_path)),
                ('Password', models.CharField(max_length=255, null=True)),
                ('RegNO', models.CharField(max_length=255, null=True)),
                ('MailingAddress', models.CharField(max_length=255, null=True)),
                ('State', models.CharField(max_length=255, null=True)),
                ('OfficeAddress', models.CharField(max_length=255, null=True)),
                ('CompanyPhoneNo', models.CharField(max_length=255, null=True)),
                ('CompanyWebsite', models.CharField(max_length=255, null=True)),
                ('DateofIncorporation', models.DateField(null=True)),
                ('TypeofBusiness', models.CharField(max_length=255, null=True)),
                ('TypeofOwnership', models.CharField(max_length=255, null=True)),
                ('AnnualTurnover', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('NameOfManagingDirector', models.CharField(max_length=255, null=True)),
                ('PhoneNoOfManagingDirector', models.CharField(max_length=255, null=True)),
                ('EmailAddressofManagingDirector', models.CharField(max_length=255, null=True)),
                ('NameofAlternate', models.CharField(max_length=255, null=True)),
                ('PhoneofAlternate', models.CharField(max_length=255, null=True)),
                ('Organizationalcharts', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('TotalStaffStrength', models.CharField(max_length=255, null=True)),
                ('MissionFirm', models.TextField(null=True)),
                ('MainActivities', models.TextField(null=True)),
                ('TypeofTraining', models.CharField(max_length=255, null=True)),
                ('coreAreas', models.TextField(null=True)),
                ('InternationalAccreditation', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('internationalAffiliations', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('AccreditationbyRelevantBody', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('CollaborativeTraining', models.TextField(null=True)),
                ('CollaborativeTrainingFile', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('RestrictionsToTraining', models.TextField(null=True)),
                ('CertificationOfFacilitators', models.TextField(null=True)),
                ('MethodsOfTraining', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('EvaluationMethods', models.TextField(null=True)),
                ('TrainingFacilitySize', models.TextField(null=True)),
                ('TrainingCapacity', models.CharField(max_length=255, null=True)),
                ('TrainingMaterials', models.TextField(null=True)),
                ('LicensesOfTrianing', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('AccommodationForTrianing', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('CertifiedTrainer', models.FileField(null=True, upload_to=Registration.models.create_path)),
                ('AreasOfGovernmentForTrianing', models.TextField(null=True)),
                ('DateInputed', models.DateTimeField(blank=True)),
            ],
        ),
    ]
